<a href="https://colab.research.google.com/github/rohansaha13/EE345-Artificial-Intelligence/blob/main/20085086_Rohan_Saha_ANN_16_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [13]:
import numpy as np
import math

In [14]:
x=np.array([0.2,-0.3]).reshape(2,1)
d=np.array([0.4,-0.3,0.5,-0.8,0.2]).reshape(5,1)

In [15]:
w1=np.array([[0.6,-0.4],[1.0,-0.9],[0.1,0.5]])
w2=np.array([[-0.5,0.3,0.1],[0.2,-0.6,0.5],[0.0,-0.4,0.6],[-0.7,-1.0,0.4]])
w3=np.array([[0.4,-0.7,0.3,0.5],[0.7,0.6,-0.2,0.9],[-0.6,0.1,-0.8,0.1],[0.8,1.0,-0.5,-0.9],[-1.0,0.0,0.2,-0.4]])

In [16]:
def sigmoid(z):
    return 1/(1+math.exp(-1*z))

def derivative_sigmoid(z):
    return sigmoid(z)*(1-sigmoid(z))

In [17]:
def forwardprop():
    global v1,xout1,v2,xout2,v3,xout3
    v1=np.matmul(w1,x)
    xout1=np.array(list(map(sigmoid,v1))).reshape(v1.shape[0],1)
    #print(xout1)
    v2=np.matmul(w2,xout1)
    xout2=np.array(list(map(sigmoid,v2))).reshape(v2.shape[0],1)
    #print(xout2)
    v3=np.matmul(w3,xout2)
    xout3=np.array(list(map(sigmoid,v3))).reshape(v3.shape[0],1)
    #print(xout3)
    return xout3

In [18]:
y=forwardprop()

def backprop():
    global le3,le2,le1
    le3=(d-y)*np.array(list(map(derivative_sigmoid,v3))).reshape(v3.shape[0],1)
    le2=np.matmul(w3.T,le3)*np.array(list(map(derivative_sigmoid,v2))).reshape(v2.shape[0],1)
    le1=np.matmul(w2.T,le2)*np.array(list(map(derivative_sigmoid,v1))).reshape(v1.shape[0],1)
    return le3,le2,le1

le3,le2,le1=backprop()
w3=w3+0.1*np.matmul(le3,xout2.T)
#print(np.matmul(le3,xout2.T))
w2=w2+0.1*np.matmul(le2,xout1.T)
#print(np.matmul(le2,xout1.T))
w1=w1+0.1*np.matmul(le1,x.T)
#print(np.matmul(le1,x.T))

In [19]:
print("w1 =")
print(w1)
print("w2 =")
print(w2)
print("w3 =")
print(w3)

w1 =
[[ 0.6000609  -0.40009135]
 [ 0.99997026 -0.89995539]
 [ 0.09984943  0.50022586]]
w2 =
[[-0.5057344   0.29369524  0.09520988]
 [ 0.19390636 -0.60669973  0.4949098 ]
 [ 0.00230131 -0.3974698   0.60192235]
 [-0.69863301 -0.99849705  0.40114189]]
w3 =
[[ 0.39831956 -0.70170193  0.29824823  0.49894696]
 [ 0.68968809  0.58955618 -0.21074968  0.89353808]
 [-0.59833394  0.10168738 -0.79826321  0.10104403]
 [ 0.78359494  0.98338508 -0.51710151 -0.91028018]
 [-1.00200862 -0.00203431  0.19790611 -0.40125869]]
